### ISSUE TITLE
Exception when reading model

### ISSUE THREAD

**Issue by ellefthurmann** [sql-bi/VertiPaq-Analyzer#142]
PS C:\Users\E> dotnet tool install Dax.Vpax.CLI --global
Tool 'dax.vpax.cli' was reinstalled with the stable version (version '1.2.2').

PS C:\Users\E> vpax export $env:VPAX_PATH $env:TABULAR_CONNECTION_STRING
Extracting VPAX metadata...Unhandled exception: Microsoft.AnalysisServices.AdomdClient.AdomdErrorResponseException: <ccon>Expression.Error: [14,94-14,116] The name 't6.Qty Reserved_445' doesn't exist in the current context.. {[...]}. </ccon>. The exception was raised by the IDbCommand interface.

```
Technical Details:
RootActivityId: 0a30b90e-c3b1-4905-b546-86ebe383db59
Date (UTC): 9/2/2024 6:56:21 AM
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForSoapFault(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.CheckForError(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.SendMessage(Boolean endReceivalIfException, Boolean readSession, Boolean readNamespaceCompatibility)
   at Microsoft.AnalysisServices.AdomdClient.XmlaClient.ExecuteStatement(String statement, IDictionary connectionProperties, IDictionary commandProperties, IDataParameterCollection parameters, Boolean isMdx)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Microsoft.AnalysisServices.AdomdClient.IExecuteProvider.ExecuteTabular(CommandBehavior behavior, ICommandContentProvider contentProvider, AdomdPropertyCollection commandProperties, IDataParameterCollection parameters)
   at Microsoft.AnalysisServices.AdomdClient.AdomdCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.AnalysisServices.AdomdClient.AdomdCommand.ExecuteReader()
   at Microsoft.AnalysisServices.AdomdClient.AdomdCommand.System.Data.IDbCommand.ExecuteReader()
   at Dax.Model.Extractor.StatExtractor.LoadColumnStatistics(Boolean analyzeDirectQuery, DirectLakeExtractionMode analyzeDirectLake, Int32 columnBatchSize)
   at Dax.Model.Extractor.StatExtractor.UpdateStatisticsModel(Model daxModel, IDbConnection connection, Int32 sampleRows, Boolean analyzeDirectQuery, DirectLakeExtractionMode analyzeDirectLake, Int32 columnBatchSize)
   at Dax.Model.Extractor.TomExtractor.GetDaxModel(String connectionString, String applicationName, String applicationVersion, Boolean readStatisticsFromData, Int32 sampleRows, Boolean analyzeDirectQuery, DirectLakeExtractionMode analyzeDirectLake, Int32 statsColumnBatchSize)
   at Dax.Vpax.CLI.Commands.ExportCommandHandler.InvokeAsync(InvocationContext context) in /home/runner/work/VertiPaq-Analyzer/VertiPaq-Analyzer/src/Dax.Vpax.CLI/Commands/ExportCommandHandler.cs:line 36
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by marcosqlbi** [comment]
Do you get a similar error by using DAX Studio and try to export the VPAX of the same model?

**Comment by ellefthurmann** [comment]
DAX studio was able to "Export Metrics" to a vpax file - here's the gui log:

9/2/2024 9:27:18 AM		Establishing Connection
9/2/2024 9:27:28 AM		The following error occurred while updating the connection: An item with the same key has already been added.
9/2/2024 9:27:30 AM		Error setting selected database: One or more errors occurred.
9/2/2024 9:27:30 AM		Error setting selected database: Object reference not set to an instance of an object.
9/2/2024 9:27:47 AM		Error refreshing table list: An item with the same key has already been added.
9/2/2024 9:28:15 AM		Saving C:\Users\EllefThurmann\Downloads\Retail Stock Historic.vpax...
9/2/2024 9:28:24 AM		Model Metrics exported successfully

**Comment by albertospelta** [comment]
@ellefthurmann The error occurs during the execution of the column statistics analysis query in Vertipaq-Analyzer. The message `Expression.Error: [14,94-14,116] The name 't6.Qty Reserved_445' doesn't exist in the current context` likely indicates an issue in the M query. Could you please check if there are any errors in the M expressions within your model where the `t6.Qty Reserved_445` name is referenced?

**Comment by marcosqlbi** [comment]
@ellefthurmann please also check the settings in DAX Studio and make sure you are exporting the full statistics (enable Read Statistics from data if the model is in import mode - or is your model DirectQuery?)
https://daxstudio.org/docs/features/model-metrics/

**Comment by ellefthurmann** [comment]
I was able to reproduce the issue when also exporting statistics from directquery model

The column QTY Reserved_445 does not exist in underlying database view - so the fault is our own!

**Comment by marcosqlbi** [comment]
Thank you for closing the loop!
